name: Windows EXE build python 3.7 PyInstaller 3.4 experiment

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Instaloader repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Run custom python script for EXE creation
        run: python deploy/windows/create_exe.py
      - name: Upload instaloader EXE artifact
        uses: actions/upload-artifact@v1
        with:
          name: instaloader-windows-standalone
          path: dist
      - name: Upload build artifact for debugging
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
